# Generated by Django 5.0.4 on 2025-03-26 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersubscription',
            name='enable_whatsapp_alerts',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='whatsapp_phone_number',
            field=models.CharField(blank=True, help_text='WhatsApp number with country code (e.g., +1234567890)', max_length=15, null=True),
        ),
    ]
