# Generated by Django 5.0.4 on 2025-03-26 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_usersubscription_latitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersubscription',
            name='latitude',
            field=models.FloatField(help_text='Latitude coordinate'),
        ),
        migrations.AlterField(
            model_name='usersubscription',
            name='longitude',
            field=models.FloatField(help_text='Longitude coordinate'),
        ),
    ]
